### ISSUE TITLE
Segfaults when app window loses focus, resizes, etc

### ISSUE THREAD

**Issue by willbprog127** [willbprog127/spiritvnc-fltk-no-libssh2#1]
With libfltk 1.3.8-4 on Linux Mint 21 Vanessa x86_64, fluxbox as window manager and x11 session, SpiritVNC-FLTK-no-libssh2 will crash / segfault at line 707 of vnc.cxx at the `Fl::wait()` call.  When I debug under `gdb` the backtrace is 149,729 lines long!  Most of the lines are just repeating the following:

```
#149715 0x00007ffff7f0d7d7 in Fl_Widget::take_focus() () from /lib/x86_64-linux-gnu/libfltk.so.1.3
No symbol table info available.
#149716 0x00007ffff7eca9e1 in Fl_Group::handle(int) () from /lib/x86_64-linux-gnu/libfltk.so.1.3
No symbol table info available.
#149717 0x00007ffff7f0d7d7 in Fl_Widget::take_focus() () from /lib/x86_64-linux-gnu/libfltk.so.1.3
No symbol table info available.
#149718 0x00007ffff7eca9e1 in Fl_Group::handle(int) () from /lib/x86_64-linux-gnu/libfltk.so.1.3
```

I have no idea what is causing this.  It looks like an FLTK issue but I'm uncertain where.  I'm busy with other projects so I don't have time to dive into this now.  

At this point FLTK and libvncclient have really not worked out well for this, so I'm considering moving to Gtk and Gtk-Vnc although that's not the greatest direction either.  It might just be time to abandon ship...?

**Comment by willbprog127** [comment]
https://github.com/willbprog127/spiritvnc-fltk-no-libssh2/commit/2078c7659528d9aa75171f113814207ea6a405a6 appears to fix this issue.  If it creeps up again, will reopen this.
